# kustomization file including different overays over the
# reference crs
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example-overlays-config/gitops/
  - example-overlays-config/acm/
  - reference-crs/required/talm/
  - reference-crs/required/gitops/ztp-installation
